[[constraint]]
  name = "github.com/cloudfoundry/bosh-davcli"
  revision = "37f54c6"
[[constraint]]
  name = "github.com/cloudfoundry/bosh-utils"
  revision = "ff59874"
[[constraint]]
  name = "github.com/golang/mock"
  revision = "15f8b22"
[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  revision = "2caf8ef"
[[constraint]]
  name = "github.com/onsi/ginkgo"
[[constraint]]
  name = "github.com/onsi/gomega"
[[constraint]]
  name = "golang.org/x/crypto"
  revision = "1e856cb"
[[constraint]]
  name = "gopkg.in/check.v1"
  revision = "8d49746"
[[constraint]]
  name = "github.com/pivotal-golang/yaml"
  revision = "8b09e4a"
[[constraint]]
  name = "github.com/vito/go-interact"
  revision = "c573392"
[[constraint]]
  name = "github.com/cheggaaa/pb"
  revision = "c1f48d5"
[[constraint]]
  name = "github.com/cppforlife/go-semi-semantic"
  revision = "576b6af"
[[constraint]]
  name = "github.com/dustin/go-humanize"
  revision = "9436b7a"
[[constraint]]
  name = "github.com/fatih/color"
  revision = "533cd7f"
[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  revision = "d30f099"
[[constraint]]
  name = "github.com/jessevdk/go-flags"
  revision = "4cc2832"
[[constraint]]
  name = "github.com/mattn/go-isatty"
  revision = "56b76bd"
[[constraint]]
  name = "github.com/mattn/go-colorable"
  revision = "e8a10dd"
[[constraint]]
  name = "github.com/go-ini/ini"
  revision = "12f418c"
[[constraint]]
  name = "github.com/jmespath/go-jmespath"
  revision = "0b12d6b"
[[constraint]]
  name = "github.com/charlievieth/fs"
  revision = "1c3b3f1"
[[constraint]]
  name = "github.com/hashicorp/errwrap"
  revision = "7554cd9"
[[constraint]]
  name = "github.com/bmatcuk/doublestar"
  revision = "dd6a6f0"
[[constraint]]
  name = "github.com/cppforlife/go-patch"
  revision = "37a72c6"
[[constraint]]
  name = "github.com/pivotal-golang/s3cli"
  revision = "90561c0"
[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "98fa357"
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  revision = "1a651d9"
[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "a5b47d3"
[[constraint]]
  name = "github.com/armon/go-socks5"
  revision = "e753329"
[[constraint]]
  name = "github.com/cloudfoundry/config-server"
  revision = "a76bda8"
[[constraint]]
  name = "github.com/cloudfoundry/gosigar"
  revision = "dfaa4d4"
[[constraint]]
  name = "github.com/pivotal/go-smtpd"
  revision = "0af6982"
[[constraint]]
  name = "github.com/jeromer/syslogparser"
  revision = "0e4ae46"
[[constraint]]
  name = "golang.org/x/net"
  revision = "5b58a9c"
[[constraint]]
  name = "golang.org/x/text"
  revision = "19e5161"
[[constraint]]
  name = "golang.org/x/sys"
  revision = "a55a760"
[[constraint]]
  name = "github.com/tedsuo/ifrit"
  revision = "08b0eee"
[[constraint]]
  name = "github.com/cloudfoundry/bosh-agent"
  revision = "6898825"
[[constraint]]
  name = "github.com/cloudfoundry/bosh-gcscli"
  revision = "e8cfa90"
[[constraint]]
  name = "cloud.google.com/go/storage"
  revision = "033c628"
[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "cce311a"
[[constraint]]
  name = "google.golang.org/api/option"
  revision = "e6586c9"
