required = ["github.com/onsi/ginkgo/ginkgo", "github.com/maxbrunsfeld/counterfeiter"]

[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  branch = "cli-patches"
  name = "github.com/jessevdk/go-flags"
  source = "github.com/cppforlife/go-flags"

[[constraint]]
  name = "github.com/cloudfoundry/bosh-utils"
  branch = "master"

# dep ensure issue in https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
