required = ["github.com/onsi/ginkgo/ginkgo", "github.com/maxbrunsfeld/counterfeiter"]

[[constraint]]
  branch = "cli-patches"
  name = "github.com/jessevdk/go-flags"
  source = "github.com/cppforlife/go-flags"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/bosh-utils"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/bosh-davcli"

[[constraint]]
  name = "github.com/cloudfoundry/bosh-s3cli"
  version = "v0.0.64"

[[constraint]]
  name = "github.com/cloudfoundry/bosh-agent"
  revision = "a74fc7069b604abe84f1ddd899f58ae1e6b1f8ee"

[[constraint]]
  name = "github.com/vito/go-interact"
  revision = "60caa86f173a89ef7a479fa400cc50faf6a2e369"
