---
jobs:
  - name: test
    plan:
      - get:      bosh-init
      - aggregate:
        - task:   test-unit
          file:   bosh-init/ci/concourse/jobs/test-unit.yml
        - task:   test-integration
          file:   bosh-init/ci/concourse/jobs/test-integration.yml
        # - task:   test-acceptance
        #   file:   bosh-init/ci/concourse/jobs/test-acceptance.yml

  - name: bump
    plan:
      - get:      bosh-init
        passed:   [test]
      - get:      version-semver
        trigger:  false
        params:   { bump: patch }
      - task:     prepare-version
        file:     bosh-init/ci/concourse/jobs/prepare-version.yml
      - aggregate:
        - put:    version-semver
          params: { file: version-semver/number }
        - put:    version-label
          params: { file: current-label }

  - name: build
    plan:
      - get:      bosh-init
        passed:   [bump]
      - get:      version-semver
        passed:   [bump]
      - get:      version-label
        passed:   [bump]
      - aggregate:
        - task:   build-linux
          file:   bosh-init/ci/concourse/jobs/build-linux.yml
        - task:   build-darwin
          file:   bosh-init/ci/concourse/jobs/build-darwin.yml
      - aggregate:
        # - put:    bosh-init
        #   params: { tag: version-semver/number, tag_prefix: v }
        - put:    release-bucket-linux
          params: { from: bosh-init/out/bosh-init-.*-linux-amd64 }
        - put:    release-bucket-darwin
          params: { from: bosh-init/out/bosh-init-.*-darwin-amd64 }

  - name: bump-minor
    plan:
      - get:      version-semver
        trigger:  false
        params:   { bump: minor }
      - put:      version-semver
        params:   { file: version-semver/number }

  - name: bump-major
    plan:
      - get:      version-semver
        trigger:  false
        params:   { bump: major }
      - put:      version-semver
        params:   { file: version-semver/number }

resources:
  - name: bosh-init
    type:       git
    source:
      uri:      https://github.com/cloudfoundry/bosh-init.git
      branch:   concourse-version

  - name: release-bucket-linux
    type:       s3
    source:
      regexp:             bosh-init-(.*)-linux-amd64
      bucket:             {{aws_bucket}}
      region_name:        {{aws_region}}
      access_key_id:      {{aws_access_key}}
      secret_access_key:  {{aws_secret_key}}

  - name: release-bucket-darwin
    type:       s3
    source:
      regexp:             bosh-init-(.*)-darwin-amd64
      bucket:             {{aws_bucket}}
      region_name:        {{aws_region}}
      access_key_id:      {{aws_access_key}}
      secret_access_key:  {{aws_secret_key}}

  - name: version-label
    type:       s3
    source:
      regexp:             current-label
      bucket:             {{aws_bucket}}
      region_name:        {{aws_region}}
      access_key_id:      {{aws_access_key}}
      secret_access_key:  {{aws_secret_key}}

  - name: version-semver
    type:       semver
    source:
      key:                current-version
      bucket:             {{aws_bucket}}
      access_key_id:      {{aws_access_key}}
      secret_access_key:  {{aws_secret_key}}
