resources:
  - name: bosh-init
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-init.git
      branch: concourse

  - name: release
    type: s3
    source:
      bucket: bosh-init-releases
      regexp: bosh-init-(.*).tgz

jobs:
  - name: test-unit
    plan:
      - get: bosh-init
        trigger: false
      - task: unit
        file: bosh-init/ci/concourse/test-unit.yml

  - name: package
    plan:
      - get: bosh-init
        passed: [test-unit]
      - task: package
        file: bosh-init/ci/concourse/package.yml
      - put: release
        params:
          from: package/*.tgz
