---
platform: linux

image: docker:///bosh/init

inputs:
- name: bosh-cli
  path: gopath/src/github.com/cloudfoundry/bosh-init
- name: version-semver

outputs:
- name: compiled-darwin

params:
  GOOS:   darwin
  GOARCH: amd64
  BOSHIO_BEARER_TOKEN: replace_me

run:
  path: gopath/src/github.com/cloudfoundry/bosh-init/ci/tasks/build.sh
