---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/cli
    tag: 'latest'

inputs:
- name: bosh-cli
- name: version-semver

outputs:
- name: compiled-darwin

params:
  GOOS:   darwin
  GOARCH: amd64
  FILENAME_PREFIX: ''

run:
  path: bosh-cli/ci/tasks/build.sh
