---
platform: linux

image: docker:///bosh/init

inputs:
- name: bosh-cli
  path: gopath/src/github.com/cloudfoundry/bosh-cli
- name: version-semver

outputs:
- name: compiled-linux

params:
  GOOS:   linux
  GOARCH: amd64
  BOSHIO_BEARER_TOKEN: replace_me

run:
  path: gopath/src/github.com/cloudfoundry/bosh-cli/ci/tasks/build.sh
