---
platform: linux

image: docker:///bosh/init

inputs:
- name: bosh-cli
  path: gopath/src/github.com/cloudfoundry/bosh-cli

run:
  path: gopath/src/github.com/cloudfoundry/bosh-cli/ci/tasks/test-integration.sh
