---
platform: linux

image: docker:///bosh/init

inputs:
- name: bosh-cli
  path: gopath/src/github.com/cloudfoundry/bosh-init

run:
  path: gopath/src/github.com/cloudfoundry/bosh-init/ci/tasks/test-unit.sh
