---
name: test-release

resource_pools:
- name: fake-resource-pool-name

networks:
- name: fake-network-name
  type: manual
  cloud_properties:
    subnet: fake-subnet
    range: 10.244.0.40/30
    reserved:
    - 10.244.0.41
    static:
    - 10.244.0.42

cloud_provider:
  ssh_tunnel:
    host: 10.244.0.42
    port: 22
    user: vcap
    password: c1oudc0w
  registry:
    host: 127.0.0.1
    port: 6301
    username: fake-registry-user
    password: fake-registry-password
  mbus: https://admin:admin@10.244.0.42:6868
  properties:
    cpi:
      warden:
        connect_network: tcp
        connect_address: 0.0.0.0:7777
        network_pool: 10.244.0.0/16
        host_ip: 192.168.54.4
      agent_env_service: registry
      registry:
        host: 127.0.0.1
        port: 6301
        username: fake-registry-user
        password: fake-registry-password
      agent:
        mbus: https://admin:admin@0.0.0.0:6868
        blobstore:
          provider: local
          options:
            blobstore_path: /var/vcap/micro_bosh/data/cache

jobs:
- name: bosh
  templates:
  - name: nats
  - name: redis
  - name: postgres
  - name: powerdns
  - name: blobstore
  - name: director
  - name: health_monitor
  networks:
  - name: fake-network-name
    static_ips:
    - 10.244.0.42
  properties:
    external_cpi:
      enabled: true
    micro: true
    nats:
      user: "nats"
      password: "nats"
      auth_timeout: 3
      address: "127.0.0.1"
      listen_address: "0.0.0.0"
      port: 4222
      no_epoll: false
      no_kqueue: true
      ping_interval: 5
      ping_max_outstanding: 2
      http:
        port: 9222
    redis:
      address: "127.0.0.1"
      password: "redis"
      port: 25255
      loglevel: "info"
    postgres:
      user: "postgres"
      password: "postges"
      host: "127.0.0.1"
      listen_address: "127.0.0.1"
      database: "bosh"
      port: 5432
      adapter: "postgres"
      connection_options:
        max_connections: 32
        pool_timeout: 10
    blobstore:
      address: "127.0.0.1"
      director:
        user: "director"
        password: "director"
      agent:
        user: "agent"
        password: "agent"
      port: 25250
      backend_port: 25251
      provider: "dav"
      s3_port: 443
      s3_force_path_style: false
      ssl_verify_peer: true
      s3_multipart_threshold: 16777216
    director:
      address: "127.0.0.1"
      name: "micro"
      port: 25555
      db:
        user: "postgres"
        password: "postges"
        host: "127.0.0.1"
        listen_address: "127.0.0.1"
        database: "bosh"
        port: 5432
        adapter: "postgres"
        connection_options:
          max_connections: 32
          pool_timeout: 10
      backend_port: 25556
      nginx:
        workers: 2
      timeout: 7200
      proxy_timeout: 900
      max_upload_size: "5000m"
      encryption: false
      max_tasks: 500
      max_threads: 32
      enable_snapshots: false
      snapshot_schedule: "0 0 7 * * * UTC"
      self_snapshot_schedule: "0 0 6 * * * UTC"
      auto_fix_stateful_nodes: true
      max_vm_create_tries: 5
    hm:
      http:
        user: "hm"
        password: "hm"
        port: 25923
      director_account:
        user: "admin"
        password: "admin"
      intervals:
        log_stats: 300
        agent_timeout: 180
        rogue_agent_alert: 180
        prune_events: 30
        poll_director: 60
        poll_grace_period: 30
        analyze_agents: 60
      loglevel: "info"
      email_notifications: false
      tsdb_enabled: false
      pagerduty_enabled: false
      varz_enabled: false
      cloud_watch_enabled: false
      resurrector_enabled: false
      resurrector:
        minimum_down_jobs: 5
        percent_threshold: 0.2
        time_threshold: 600
      datadog_enabled: false
    dns:
      address: "127.0.0.1"
      domain_name: "microbosh"
      db:
        user: "postgres"
        password: "postges"
        host: "127.0.0.1"
        listen_address: "127.0.0.1"
        database: "bosh"
        port: 5432
        adapter: "postgres"
        connection_options:
          max_connections: 32
          pool_timeout: 10
      webserver:
        port: 8081
        address: "0.0.0.0"
    compiled_package_cache:
      provider: "s3"
      options:
        port: 25250
        ssl_verify_peer: true
        s3_port: 443
        s3_force_path_style: false
        s3_multipart_threshold: 16777216
    ntp: []
    agent:
      blobstore:
        ssl_verify_peer: true
        s3_force_path_style: false
        s3_multipart_threshold: 16777216
    registry:
      http:
        port: 25777
    openstack:
      endpoint_type: "publicURL"
      state_timeout: 300
      stemcell_public_visibility: false
      wait_resource_poll_interval: 5
    vcd:
      entities:
        vm_metadata_key: "vcd-cf"
        description: "vcd-cf"
    event_nats_enabled: false
