---
groups:
- name: all
  jobs:
  - build

jobs:
  - name: build
    public: true
    plan:
      - aggregate:
        - get: bosh-cli
        - get: version-semver
          params: {bump: patch}
      - aggregate:
        - task: build-linux
          file: bosh-cli/ci/tasks/build-linux.yml
        - task: build-darwin
          file: bosh-cli/ci/tasks/build-darwin.yml
        - task: build-windows
          file: bosh-cli/ci/tasks/build-windows.yml

      - task: build-checksum-file
        file: bosh-cli/ci/tasks/build-checksum-file.yml

      # - put: bosh-cli-commit-status
      #   params:
      #     state: success
      #     commit: bosh-cli

      - aggregate:
        - {put: bosh-cli-promoted, params: {repository: bosh-cli, tag: version-semver/number, tag_prefix: v}}

      - put: github-release
        params:
          name: version-semver/number
          tag: version-semver/number
          tag_prefix: v
          globs:
            - compiled-linux/bosh-cli-*-linux-amd64
            - compiled-darwin/bosh-cli-*-darwin-amd64
            - compiled-windows/bosh-cli-*-windows-amd64.exe
          body: checksums/checksums

resources:
  - name: bosh-cli
    type: git
    source:
      uri: git@github.com:bosh-ci-push-pull/bosh-cli.git
      branch: develop
      private_key: {{concourse_github_private_key}}


  # - name: bosh-cli-commit-status
  #   type: github-status
  #   source:
  #     repository: cloudfoundry/bosh-cli
  #     access_token: {{repo_github_token}}
  #     branch: develop
  #     context: ci/published

  - name: version-semver
    type: semver
    source:
      initial_version: 0.0.1
      key: cli-current-version
      bucket: {{aws_s3_release_bucket}}
      access_key_id: {{aws_s3_release_bucket_access_key}}
      secret_access_key: {{aws_s3_release_bucket_secret_key}}

  - name: github-release
    type: github-release
    source:
      owner: bosh-ci-push-pull
      repository: bosh-cli
      access_token: {{github_release_token}}


# resource_types:
#   - name: github-status
#     type: docker-image
#     source:
#       repository: dpb587/github-status-resource
#       tag: master
