---
jobs:
  - name: test-unit
    public: true
    plan:
      - get: bosh-cli
        trigger: true
      - task: test-unit
        file: bosh-cli/ci/tasks/test-unit.yml

  - name: test-integration
    public: true
    plan:
      - get: bosh-cli
        trigger: true
      - task: test-integration
        file: bosh-cli/ci/tasks/test-integration.yml
        privileged: true

  - name: test-acceptance
    public: true
    plan:
      - aggregate:
        - get: bosh-warden-stemcell-agentv2
        - get: bosh-cli
          passed: [test-unit,test-integration]
          trigger: true
        - get: bosh-warden-cpi-release
          trigger: true
      - aggregate:
        - task: test-acceptance
          file: bosh-cli/ci/tasks/test-acceptance.yml
          privileged: true

  - name: integration-postgres
    public: true
    serial: true
    build_logs_to_retain: 250
    plan:
      - aggregate:
        - get: bosh-src
          trigger: true
        - get: bosh-cli
          passed: [test-unit,test-integration]
          trigger: true
        - get: bosh-agent
          trigger: true
        - get: integration-tests-parallel-runtime
        - get: version-semver
          params: {bump: patch}

      - task: build-linux
        file: bosh-cli/ci/tasks/build-linux.yml

      - task: tests
        privileged: true
        input_mapping:
          bosh-cli: compiled-linux
        file: bosh-src/ci/tasks/test-integration-gocli.yml
        tags: ["bosh-integration"]
        params:
          DB: postgresql


  - name: build-alpha
    public: true
    plan:
      - aggregate:
        - get: bosh-cli
          passed:
           - test-acceptance
           - integration-postgres
          trigger: true
        - get: alpha-version-semver
          params: {bump: patch}
      - {put: alpha-version-semver, params: {file: alpha-version-semver/number}}
      - aggregate:
        - task: build-linux
          input_mapping: {version-semver: alpha-version-semver}
          file: bosh-cli/ci/tasks/build-linux.yml
          params:
            FILENAME_PREFIX: "alpha-"
        - task: build-darwin
          input_mapping: {version-semver: alpha-version-semver}
          file: bosh-cli/ci/tasks/build-darwin.yml
          params:
            FILENAME_PREFIX: "alpha-"
        - task: build-windows
          input_mapping: {version-semver: alpha-version-semver}
          file: bosh-cli/ci/tasks/build-windows.yml
          params:
            FILENAME_PREFIX: "alpha-"

      - aggregate:
        - {put: alpha-release-bucket-linux, params: {file: compiled-linux/alpha-bosh-cli-*-linux-amd64}}
        - {put: alpha-release-bucket-darwin, params: {file: compiled-darwin/alpha-bosh-cli-*-darwin-amd64}}
        - {put: alpha-release-bucket-windows, params: {file: compiled-windows/alpha-bosh-cli-*-windows-amd64.exe}}

resources:
  - name: version-semver
    type: semver
    source:
      initial_version: 0.0.1
      key: cli-current-version
      bucket: {{aws_s3_release_bucket}}
      access_key_id: {{aws_s3_release_bucket_access_key}}
      secret_access_key: {{aws_s3_release_bucket_secret_key}}

  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: external-cpi-refactor

  - name: bosh-agent
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-agent.git
      branch: registry-removal

  - name: bosh-cli
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-cli.git
      branch: external-cpi-refactor

  - name: bosh-warden-cpi-release
    type: bosh-io-release
    source:
      repository: cppforlife/bosh-warden-cpi-release

  - name: bosh-warden-stemcell-agentv2
    type: s3
    source:
      bucket: bosh-toronto-bag
      regexp: bosh-registry-removal/stemcells/warden/bosh-stemcell-(.*)-warden-boshlite-ubuntu-trusty-go_agent.tgz

  - name: integration-tests-parallel-runtime
    type: s3
    source:
      bucket: ((integration_runtime_bucket))
      access_key_id: ((integration_runtime_access_key_id))
      secret_access_key: ((integration_runtime_secret_access_key))
      versioned_file: "parallel_runtime_rspec.log"

  - name: alpha-version-semver
    type: semver
    source:
      initial_version: 0.0.1
      key: bosh-registry-removal/bosh-cli/cli-alpha-current-version
      bucket: bosh-toronto-bag
      region_name: {{aws_region}}
      access_key_id: {{aws_access_key}}
      secret_access_key: {{aws_secret_key}}

  - name: alpha-release-bucket-linux
    type: s3
    source:
      regexp: bosh-registry-removal/bosh-cli/alpha-bosh-cli-(.*)-linux-amd64
      bucket: bosh-toronto-bag
      region_name: {{aws_region}}
      access_key_id: {{aws_access_key}}
      secret_access_key: {{aws_secret_key}}

  - name: alpha-release-bucket-darwin
    type: s3
    source:
      regexp: bosh-registry-removal/bosh-cli/alpha-bosh-cli-(.*)-darwin-amd64
      bucket: bosh-toronto-bag
      region_name: {{aws_region}}
      access_key_id: {{aws_access_key}}
      secret_access_key: {{aws_secret_key}}

  - name: alpha-release-bucket-windows
    type: s3
    source:
      regexp: bosh-registry-removal/bosh-cli/alpha-bosh-cli-(.*)-windows-amd64.exe
      bucket: bosh-toronto-bag
      region_name: {{aws_region}}
      access_key_id: {{aws_access_key}}
      secret_access_key: {{aws_secret_key}}

resource_types:
  - name: github-status
    type: docker-image
    source:
      repository: dpb587/github-status-resource
      tag: master
